day32/day32/urls.py
from django.contrib import admin
from django.urls import path,re_path

from app01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.index),
    re_path(r'ab_json/',views.ab_json),
    re_path(r'ab_file/',views.ab_file),
    re_path(r'ab_ser/',views.ab_ser),
    re_path(r'user/list/',views.user_list),
    re_path(r'delete/user/',views.delete_user),
    re_path(r'adds/datas/',views.ab_adds),
    re_path(r'users/lists/',views.user_list),
    re_path(r'regedit/user/',views.reg),
]

day32/app01/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=32)
    age = models.IntegerField()
    gender_choices = (
        (1, '男'),
        (2, '女'),
        (3, '其他'),
    )
    gender = models.IntegerField(choices=gender_choices)

    score_choices = (
        ('A', '优秀'),
        ('B', '良好'),
        ('C', '及格'),
        ('D', '不合格'),
    )

    score = models.CharField(max_length=32, choices=score_choices, null=True)

    te = models.ForeignKey(to='Te', on_delete=models.CASCADE)


class Te(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=32)
    phone = models.BigIntegerField(verbose_name='手机号码', unique=True, null=True)
    job = models.CharField(max_length=32, verbose_name='职业', blank=True, null=True, default='IT')  # blank表单认证,字段填写不为空
    date = models.DateField(verbose_name='date', help_text='yyyy-mm-dd', blank=True, null=True)


class Book(models.Model):
    name = models.CharField(verbose_name='书名', max_length=64)
    publish = models.CharField(verbose_name='出版社名', max_length=32)
    authors = models.ManyToManyField(to='Author',
                                     through='Book2Author',
                                     through_fields=('book', 'author')
                                     )


class Publish(models.Model):
    name = models.CharField(max_length=32)


class Book2Publish(models.Model):
    book_id = models.ForeignKey(to='Book', on_delete=models.CASCADE)
    publish_id = models.ForeignKey(to='Publish', on_delete=models.CASCADE)


class Author(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()


class Book2Author(models.Model):
    book = models.ForeignKey(to='Book', on_delete=models.CASCADE)
    author = models.ForeignKey(to='Author', on_delete=models.CASCADE)

day32/templates/ab_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
<p>username:<input type="text" id="username"></p>
<p>password:<input type="password" id="password"></p>
<p><input type="file" id="file1"></p>
<button class="btn btn-primary" id="button1">提交</button>


<script>
    $('#button1').on('click',function () {
        let formDateObj = new FormData;
        formDateObj.append('username',$('#username').val());
        formDateObj.append('password',$('#password').val());

        formDateObj.append('file',$('#file1')[0].files[0]); //两个对象之间的转换
        $.ajax({
            url:'',
            type:'post',
            data:formDateObj,
            contentType:false,
            processData:false,
            success:function (args) {
                
            }
        })
    })

</script>
</body>
</html>

day32/templates/ab_json.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
<form action="" method="post">

    <button class="btn btn-danger" id="d1">提交</button>
</form>



<script>
    $('#d1').click(function () {
        $.ajax({
            url:'',
            type:'post',
            data:JSON.stringify({'username':'json','age':55}),
            contentType:'application.json',   // 不写默认是urlencoded
            success:function (){

            }
        })
    })
</script>

</body>
</html>

day32/templates/ab_ser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
{% for user_obj in user_queryset %}
    <p>{{ user_obj }}</p>
{% endfor %}



</body>
</html>

day32/templates/add_dates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <style>
        div.sweet-alert h2{
            padding-top: 4px;
        }
    </style>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
<div class="container-fluid">
    <h1 class="text-center">UserList</h1>
    <div class="row">
        <div class="col-md-12 col-md-auto">
            <table class="table-striped table-hover table">
                <thead>
                 <tr>
                     <td><i class="fa-brands fa-ideal"></i>ID</td>
                     <td><i class="fa-solid fa-user"></i>Username</td>
                     <td><i class="fa-solid fa-calendar"></i>Age</td>
                     <td><i class="fa-solid fa-person-half-dress"></i>Gender</td>
                     <td><i class="fa-solid fa-user-secret"></i>Score</td>
                     <td><i class="fa-solid fa-desktop"></i>Te</td>
                     <td><i class="fa-solid fa-screwdriver-wrench"></i>Action</td>
                 </tr>
                </thead>
{#                <tbody>#}
{#                 {% for user_obj in user_queryset_list %}#}
{#                   <tr>#}
{#                       <td>{{ user_obj.pk }}</td>#}
{#                       <td>{{ user_obj.username }}</td>#}
{#                       <td>{{ user_obj.age }}</td>#}
{#                       <td>{{ user_obj.get_gender_display }}</td>#}
{#                       <td>{{ user_obj.get_score_display }}</td>#}
{#                       <td>{{ user_obj.te.id }}</td>#}
{#                       <td>#}
{#                           <button class="btn btn-primary btn-sm">编辑</button>#}
{#                           <button class="btn btn-danger btn-sm del" delete_id="{{ user_obj.pk }}">删除</button>#}
{#                       </td>#}
{#                   </tr>#}
{##}
{##}
{#                 {% endfor %}#}
{##}
{##}
{#                </tbody>#}

                <tbody>
                   {% for user_obj in page_queryset %}
                     <tr>
                         <td>{{ user_obj.pk }}</td>
                         <td>{{ user_obj.username }}</td>
                         <td>{{ user_obj.age }}</td>
                         <td>{{ user_obj.get_gender_display }}</td>
                         <td>{{ user_obj.get_score_display }}</td>
                         <td>{{ user_obj.id }}</td>
                         <td>
                             <button class="btn btn-primary btn-sm">编辑</button>
                             <button class="btn btn-danger btn-sm del" delete_id="{{ user_obj.pk }}">删除</button>
                         </td>
                     </tr>
                   {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>


<nav aria-label="..." class="d-flex justify-content-center">
  <ul class="pagination">
{#    <li class="page-item">#}
{#      <a aria-label="Previous" class="page-link" href="?page={{ x }}">#}
{#          <span aria-hidden="true">Previous</span>#}
{#      </a>#}
{#    </li>#}
{#      {{ Previous|safe }}#}
{#    <li class="page-item active"  aria-current="page"><a class="page-link" href="#">1</a></li>#}
{#      {{ page_html|safe }}#}
{#    <li class="page-item">#}
{#      <a aria-label="Next" class="page-link" href="?page={{ xx }}">#}
{#          <span aria-hidden="true">Next</span>#}
{#      </a>#}
{#     </li>#}
{#      {{ Next|safe }}#}
      {{ page_obj.page_html|safe }}
  </ul>
</nav>

{#{% for user_obj in page_queryset %}#}
{# <p>{{ user_obj.username }}</p>#}
{#    <nav aria-label="..." class="d-flex justify-content-center">#}
{#         {{ page_obj.page_html|safe }}#}
{#    </nav>#}
{#{% endfor %}#}





{#{{ error_html|safe }}#}
{##}
{#<div class="bd-example" style="margin-left: 20%;">#}
{#        <p class="h1">Example heading <span class="badge bg-primary">New</span></p>#}
{#        <p class="h2">Example heading <span class="badge bg-secondary">New</span></p>#}
{#        <p class="h3">Example heading <span class="badge bg-success">New</span></p>#}
{#        <p class="h4">Example heading <span class="badge bg-danger">New</span></p>#}
{#        <p class="h5">Example heading <span class="badge bg-warning text-dark">New</span></p>#}
{#        <p class="h6">Example heading <span class="badge bg-info text-dark">New</span></p>#}
{#        <p class="h6">Example heading <span class="badge bg-light text-dark">New</span></p>#}
{#        <p class="h6">Example heading <span class="badge bg-dark">New</span></p>#}
{#</div>#}



<script>
    $('.del').on('click',function () {
        // 先将获取的标签对象存储起来
        let currenBtn = $(this);
        {#alert($(this).attr('delete_id'))#}

        //sweetalert
        swal({
                title: "您是否删除?",
                text: "您确定你要删除该行数据,备份过了?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes",
                cancelButtonClass: "btn-primary",
                cancelButtonText: "No, 再想想!",
                closeOnConfirm: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,  //延时3秒,动态效果
            },
        function(isConfirm) {
             if (isConfirm) {
                {#swal("已经删除!", "如果这是恶意行为监狱欢迎您!", "success");#}
                 // 向后端发送ajax请求删除数据再弹出下面的提示
                 $.ajax({
                     {#url:'/delete/user/' + currenBtn.attr('delete_id'),  //1 传递主键值方式1#}
                     url: '/delete/user/', //2 放在请求体里面
                     type:'post',
                     data:{'delete_id':currenBtn.attr('delete_id')},
                     success:function (args) {
                         if(args.code === 10086){
                             swal('删除',args.msg,"success");
                             {#window.location.reload()#}
                             currenBtn.parent().parent().remove()
                         }
                         else {
                             swal('Error','返回状态码不存在,但数据也被删除了,请联系管理员','info')
                             currenBtn.parent().parent().remove()
                         }
                     }
                 })
                }
             else {
                swal("操作被取消", "数据幸存下来!", "error");
                }
            });


        })
</script>
</body>
</html>

day32/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
{#<input type="text" id="d1"> +#}
{#<input type="text" id="d2"> =#}
{#<input type="text" id="d3">#}
{#<button id="btn" class="btn btn-dark">计算</button>#}

<form action="" method="post">
    <p>username:<input type="text" name="username" class="form-control" id="u1"></p>
    <p>password:<input type="password" name="password" class="form-control" id="p1"></p>
    <p>file:<input type="file" name="file" id="f1"></p>
    <input type="submit" class="btn btn-primary">
    <input type="button" class="btn btn-danger" id="d1" value="提交">
</form>

<script>
    $('#d1').click(function (){
        $.ajax({
            url:'',
            type:'post',
            dataType:'JSON',
            {#data:{'username':'tom','password':'123456'},#}
            data:{'i1':$('#u1').val(),'i2':$('#p1').val(),'i3':$('#f1').val()},
            success:function (args){
                alert(args)
            }
        })
    })
</script>

<a href="/users/lists">userlist</a>
<a href="ab_json">json</a>
<a href="ab_file">file</a>
<a href="ab_ser">ser</a>
<a href="regedit/user">regedit</a>
<a href=""></a>
<a href=""></a>


{#<script>#}
{#    $('#btn').click(function () {#}
{#        $.ajax({#}
{#            url: '',#}
{#            type: 'post',#}
{#            dataType: 'JSON',#}
{#            data: {'i1': $('#d1').val(), 'i2': $('#d2').val()},#}
{#            success: function (args) {#}
                {#alert(args)#}
{#                $('#d3').val(args)#}
{#                console.log(typeof args)#}
{#            }#}
{#        })#}
{#    })#}
{#</script>#}
</body>
</html>

day32/templates/reg_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>regedit</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
<div class="content">
    <form action="">
        <p>
            username: <input type="text">
            <span style="color: maroon"></span>
        </p>
        <p>
            password: <input type="password">
            <span></span>
        </p>
        <p>
            <input type="button" value="提交" class="button btn-primary">
        </p>
    </form>
</div>
</body>
</html>

day32/templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--响应式布局-->
    <title>Title</title>
    <!--django-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <style>
        div.sweet-alert h2{
            padding-top: 4px;
        }
    </style>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</head>
<body>
<div class="container-fluid">
    <h1 class="text-center">UserList</h1>
    <div class="row">
        <div class="col-md-12 col-md-auto">
            <table class="table-striped table-hover table">
                <thead>
                 <tr>
                     <td><i class="fa-brands fa-ideal"></i>ID</td>
                     <td><i class="fa-solid fa-user"></i>Username</td>
                     <td><i class="fa-solid fa-calendar"></i>Age</td>
                     <td><i class="fa-solid fa-person-half-dress"></i>Gender</td>
                     <td><i class="fa-solid fa-user-secret"></i>Score</td>
                     <td><i class="fa-solid fa-desktop"></i>Te</td>
                     <td><i class="fa-solid fa-screwdriver-wrench"></i>Action</td>
                 </tr>
                </thead>
                <tbody>
                 {% for user_obj in user_queryset %}
                   <tr>
                       <td>{{ user_obj.pk }}</td>
                       <td>{{ user_obj.username }}</td>
                       <td>{{ user_obj.age }}</td>
                       <td>{{ user_obj.get_gender_display }}</td>
                       <td>{{ user_obj.get_score_display }}</td>
                       <td>{{ user_obj.te.id }}</td>
                       <td>
                           <button class="btn btn-primary btn-sm">编辑</button>
                           <button class="btn btn-danger btn-sm del" delete_id="{{ user_obj.pk }}">删除</button>
                       </td>
                   </tr>
                 {% endfor %}

                  
                </tbody>
            </table>
        </div>
    </div>
</div>

<ul class="paginator">
    <li>
        <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        {{ page_html|safe }}
    </li>
    <li>
        <a href="#" aria-label="Next">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
</ul>


<script>
    $('.del').on('click',function () {
        // 先将获取的标签对象存储起来
        let currenBtn = $(this);
        {#alert($(this).attr('delete_id'))#}

        //sweetalert
        swal({
                title: "您是否删除?",
                text: "您确定你要删除该行数据,备份过了?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes",
                cancelButtonClass: "btn-primary",
                cancelButtonText: "No, 再想想!",
                closeOnConfirm: false,
                closeOnCancel: false
            },
        function(isConfirm) {
             if (isConfirm) {
                {#swal("已经删除!", "如果这是恶意行为监狱欢迎您!", "success");#}
                 // 向后端发送ajax请求删除数据再弹出下面的提示
                 $.ajax({
                     {#url:'/delete/user/' + currenBtn.attr('delete_id'),  //1 传递主键值方式1#}
                     url: '/delete/user/', //2 放在请求体里面
                     type:'post',
                     data:{'delete_id':currenBtn.attr('delete_id')},
                     success:function (args) {
                         if(args.code === 10086){
                             swal('删除',args.msg,"success");
                             {#window.location.reload()#}
                             currenBtn.parent().parent().remove()
                         }
                         else {
                             swal('Error','返回状态码不存在,但数据也被删除了,请联系管理员','info')
                             currenBtn.parent().parent().remove()
                         }
                     }
                 })
                }
             else {
                swal("操作被取消", "数据幸存下来!", "error");
                }
            });


        })
</script>
</body>
</html>